import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 * Created by LolHens on 11.01.2015.
 */
public class MainWindow extends JFrame {

    private JPanel panelMain;
    private JButton add;
    private JButton delete;
    private JButton refresh;
    private JTable table1;
    private DefaultTableModel t = new DefaultTableModel();

    private Connection connection;

    public MainWindow(Connection connection) throws SQLException {
        super("DATABASE");
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        this.connection = connection;
        setContentPane(panelMain);

        table1.setModel(t);
        t.addColumn("id");
        t.addColumn("nachname");
        t.addColumn("vorname");
        t.addColumn("stadt");
        t.addColumn("plz");
        t.addColumn("str");
        t.addColumn("hausnummer");

        refresh.addActionListener((event) -> {
            refresh();
        });

        delete.addActionListener((event) -> {
            Object selected = t.getValueAt(table1.getSelectedRow(), 0);
            if (selected == null) return;
            try {
                connection.createStatement().execute("DELETE FROM Schueler WHERE id_schueler=" + Integer.valueOf(selected.toString()));
            } catch (SQLException e) {
                e.printStackTrace();
            }
            refresh();
        });

        add.addActionListener((event) -> {
            new AddWindow(connection, this);
        });

        refresh();

        pack();
        setVisible(true);
    }

    public void refresh() {
        for (int i = t.getRowCount() - 1; i >= 0; i--) t.removeRow(i);

        try {
            ResultSet rs = connection.createStatement().executeQuery("SELECT * FROM Schueler");
            while (rs.next()) {
                t.addRow(new String[]{
                        rs.getString(1),
                        rs.getString(2),
                        rs.getString(3),
                        rs.getString(4),
                        rs.getString(5),
                        rs.getString(6),
                        rs.getString(7),
                });
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelMain = new JPanel();
        panelMain.setLayout(new GridLayoutManager(2, 3, new Insets(0, 0, 0, 0), -1, -1));
        final JScrollPane scrollPane1 = new JScrollPane();
        panelMain.add(scrollPane1, new GridConstraints(0, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        table1 = new JTable();
        scrollPane1.setViewportView(table1);
        refresh = new JButton();
        refresh.setText("refresh");
        panelMain.add(refresh, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        delete = new JButton();
        delete.setText("delete");
        panelMain.add(delete, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        add = new JButton();
        add.setText("add");
        panelMain.add(add, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelMain;
    }
}
